export type Language = 'en' | 'es';

export interface Translation {
  [key: string]: {
    en: string;
    es: string;
  };
}

export const translations: Translation = {
  nav_home: { en: 'Home', es: 'Inicio' },
  nav_about: { en: 'About Us', es: 'Nosotros' },
  nav_services: { en: 'Services', es: 'Servicios' },
  nav_portfolio: { en: 'Portfolio', es: 'Portafolio' },
  nav_testimonials: { en: 'Testimonials', es: 'Testimonios' },
  nav_contact: { en: 'Contact', es: 'Contacto' },
  hero_title: { en: 'High-Quality Pool Service in Central Florida', es: 'Servicio de Piscinas de Alta Calidad en Florida Central' },
  hero_subtitle: { en: 'Serving Orlando and surrounding areas with over 20 years of experience in pool maintenance, renovations, and expert solutions you can trust.', es: 'Sirviendo a Orlando y áreas circundantes con más de 20 años de experiencia en mantenimiento, renovaciones y soluciones expertas en las que puede confiar.' },
  cta_estimate: { en: 'Get Your Free In-Person Estimate', es: 'Obtenga su Presupuesto Presencial Gratuito' },
  cta_schedule: { en: 'Schedule Your Free Estimate', es: 'Programe su Presupuesto Gratuito' },
  cta_view_details: { en: 'View Details', es: 'Ver Detalles' },
  cta_view_all: { en: 'View All Services', es: 'Ver Todos los Servicios' },
  section_why_title: { en: "Why Homeowners Choose Waterland Pool's", es: "¿Por qué los propietarios eligen Waterland Pool's?" },
  footer_hours: { en: 'Business Hours', es: 'Horario de Atención' },
  footer_mon_fri: { en: 'Monday to Friday, 8:00 AM - 5:00 PM', es: 'Lunes a Viernes, 8:00 AM - 5:00 PM' },
  form_full_name: { en: 'Full Name', es: 'Nombre Completo' },
  form_phone: { en: 'Phone Number', es: 'Número de Teléfono' },
  form_email: { en: 'Email Address', es: 'Correo Electrónico' },
  form_address: { en: 'Property Address', es: 'Dirección de la Propiedad' },
  form_service: { en: 'Service Needed', es: 'Servicio Necesario' },
  form_message: { en: 'Tell Us About Your Pool', es: 'Cuéntenos sobre su piscina' },
  form_preferred_time: { en: 'Preferred Day & Time for Estimate', es: 'Día y Hora Preferidos para el Presupuesto' },
  form_submit: { en: 'Request Your Free In-Person Estimate', es: 'Solicitar Presupuesto Presencial Gratuito' },
  
  // Home Page
  home_years_excellence: { en: '20+ Years of Excellence', es: 'Más de 20 Años de Excelencia' },
  home_intro_title: { en: 'Your Pool Should Be a Place of Comfort, Beauty, and Peace of Mind.', es: 'Su piscina debe ser un lugar de confort, belleza y tranquilidad.' },
  home_intro_text: { en: "At Waterland Pool's, we believe in more than just maintenance. As a family-owned company, we deliver personalized service, consistent quality, and long-term reliability for every client we serve.", es: "En Waterland Pool's, creemos en algo más que el simple mantenimiento. Como empresa familiar, ofrecemos un servicio personalizado, calidad constante y confiabilidad a largo plazo para cada cliente al que servimos." },
  home_learn_more: { en: 'Learn more about our story', es: 'Conozca más sobre nuestra historia' },
  home_trusted_count: { en: '400+', es: '400+' },
  home_trusted_label: { en: 'Trusted Homeowners', es: 'Propietarios que Confían' },
  home_services_title: { en: 'Everything Your Pool Needs, Done Right', es: 'Todo lo que su piscina necesita, bien hecho' },
  home_services_subtitle: { en: 'From weekly service to full renovations, our team handles every detail with precision and care.', es: 'Desde el servicio semanal hasta renovaciones completas, nuestro equipo se encarga de cada detalle con precisión y cuidado.' },
  home_why_1_title: { en: 'Over 20 years of hands-on experience', es: 'Más de 20 años de experiencia práctica' },
  home_why_1_desc: { en: 'Expertise built through decades of serving Central Florida.', es: 'Experiencia construida a través de décadas sirviendo a Florida Central.' },
  home_why_2_title: { en: 'Personalized, in-person estimates', es: 'Presupuestos personalizados y presenciales' },
  home_why_2_desc: { en: 'We visit your property to understand your specific needs.', es: 'Visitamos su propiedad para entender sus necesidades específicas.' },
  home_why_3_title: { en: 'Trusted by 400+ homeowners', es: 'Con la confianza de más de 400 propietarios' },
  home_why_3_desc: { en: 'A solid reputation built on quality and commitment.', es: 'Una reputación sólida construida sobre la calidad y el compromiso.' },
  home_why_4_title: { en: 'High-end service with attention to detail', es: 'Servicio de alta gama con atención al detalle' },
  home_why_4_desc: { en: 'We treat every pool as if it were our own.', es: 'Tratamos cada piscina como si fuera la nuestra.' },
  home_ready_title: { en: 'Ready for a crystal clear pool?', es: '¿Listo para una piscina cristalina?' },
  home_ready_subtitle: { en: 'Join hundreds of satisfied homeowners in Orlando. Get your free estimate today.', es: 'Únase a cientos de propietarios satisfechos en Orlando. Obtenga su presupuesto gratuito hoy.' },

  // Services
  service_leak_title: { en: 'Leak Detection', es: 'Detección de Fugas' },
  service_leak_desc: { en: 'Leaks can lead to costly damage if not addressed early. Our specialized leak detection service identifies issues quickly and accurately.', es: 'Las fugas pueden causar daños costosos si no se abordan a tiempo. Nuestro servicio especializado de detección de fugas identifica los problemas de forma rápida y precisa.' },
  service_cleaning_title: { en: 'Pool Cleaning & Maintenance', es: 'Limpieza y Mantenimiento de Piscinas' },
  service_cleaning_desc: { en: 'Keep your pool clean, balanced, and ready to use with reliable weekly service. We handle everything from cleaning to chemical balancing.', es: 'Mantenga su piscina limpia, equilibrada y lista para usar con un servicio semanal confiable. Nos encargamos de todo, desde la limpieza hasta el equilibrio químico.' },
  service_renovations_title: { en: 'Pool & Deck Renovation', es: 'Renovación de Piscinas y Terrazas' },
  service_renovations_desc: { en: 'Upgrade your pool and outdoor space with modern renovations. From resurfacing to new pavers and design improvements.', es: 'Actualice su piscina y espacio al aire libre con renovaciones modernas. Desde el revestimiento hasta nuevos adoquines y mejoras de diseño.' },
  service_equipment_title: { en: 'Equipment Repair & Installation', es: 'Reparación e Instalación de Equipos' },
  service_equipment_desc: { en: 'We repair and install pumps, filters, heaters, and automation systems to keep your pool running efficiently and safely.', es: 'Reparamos e instalamos bombas, filtros, calentadores y sistemas de automatización para que su piscina funcione de forma eficiente y segura.' },
  service_sealing_title: { en: 'Paver Sealing', es: 'Sellado de Adoquines' },
  service_sealing_desc: { en: 'Protect your pool deck and enhance its appearance with professional paver sealing to prevent water damage and staining.', es: 'Proteja la terraza de su piscina y mejore su apariencia con un sellado profesional de adoquines para evitar daños por agua y manchas.' },
  service_acid_wash_title: { en: 'Acid Wash & Deep Cleaning', es: 'Lavado Ácido y Limpieza Profunda' },
  service_acid_wash_desc: { en: 'Restore your pool’s appearance by removing stains, algae buildup, and discoloration. Ideal for pools that need a visual reset.', es: 'Restaure la apariencia de su piscina eliminando manchas, acumulación de algas y decoloración. Ideal para piscinas que necesitan un reinicio visual.' },
  service_automation_title: { en: 'Pool Automation & Control Systems', es: 'Automatización y Sistemas de Control de Piscinas' },
  service_automation_desc: { en: 'Take full control of your pool with modern technology. Control heating, lighting, and pumps directly from your smartphone.', es: 'Tome el control total de su piscina con tecnología moderna. Controle la calefacción, la iluminación y las bombas directamente desde su teléfono inteligente.' },
  services_hero_title: { en: 'Professional Pool Services You Can Rely On', es: 'Servicios Profesionales de Piscina en los que Puede Confiar' },
  services_hero_subtitle: { en: 'We offer complete pool solutions designed to keep your pool clean, efficient, and visually stunning all year long.', es: 'Ofrecemos soluciones integrales para piscinas diseñadas para mantener su piscina limpia, eficiente y visualmente impresionante durante todo el año.' },
  services_not_sure_title: { en: 'Not sure what your pool needs?', es: '¿No está seguro de lo que necesita su piscina?' },
  services_not_sure_subtitle: { en: 'Let us take a look and recommend the best solution.', es: 'Permítanos echar un vistazo y recomendarle la mejor solución.' },

  // About
  about_hero_title: { en: 'Built on Experience. Driven by Trust.', es: 'Construido sobre la Experiencia. Impulsado por la Confianza.' },
  about_hero_subtitle: { en: "Waterland Pool's was founded in 2005 with a simple goal: to provide reliable and high-quality pool services with a personal touch.", es: "Waterland Pool's fue fundada en 2005 con un objetivo simple: proporcionar servicios de piscina confiables y de alta calidad con un toque personal." },
  about_story_p1: { en: 'Over the years, we’ve grown from a small operation into a trusted company serving hundreds of homeowners across Central Florida. Today, we maintain hundreds of pools weekly and provide full-service solutions, including renovations and advanced pool systems.', es: 'A lo largo de los años, hemos pasado de ser una pequeña operación a una empresa de confianza que atiende a cientos de propietarios en toda Florida Central. Hoy en día, mantenemos cientos de piscinas semanalmente y ofrecemos soluciones integrales, incluyendo renovaciones y sistemas avanzados de piscinas.' },
  about_story_p2: { en: 'What sets us apart is the way we work. Every project starts with a free in-person estimate, where we take the time to understand your pool, your space, and your expectations. From there, we deliver tailored solutions designed for long-term results.', es: 'Lo que nos diferencia es nuestra forma de trabajar. Cada proyecto comienza con un presupuesto presencial gratuito, donde nos tomamos el tiempo para entender su piscina, su espacio y sus expectativas. A partir de ahí, ofrecemos soluciones a medida diseñadas para obtener resultados a largo plazo.' },
  about_story_p3: { en: 'As a family-owned business, we value relationships just as much as results. Our commitment is to provide consistent service, clear communication, and a level of care that our clients can rely on.', es: 'Como empresa familiar, valoramos las relaciones tanto como los resultados. Nuestro compromiso es proporcionar un servicio constante, una comunicación clara y un nivel de atención en el que nuestros clientes puedan confiar.' },
  about_mission_title: { en: 'Mission', es: 'Misión' },
  about_mission_text: { en: 'To deliver complete pool solutions with excellence, attention to detail, and personalized service, ensuring safety, quality, and peace of mind for every client.', es: 'Ofrecer soluciones integrales para piscinas con excelencia, atención al detalle y servicio personalizado, garantizando la seguridad, calidad y tranquilidad de cada cliente.' },
  about_vision_title: { en: 'Vision', es: 'Visión' },
  about_vision_text: { en: 'To be recognized as one of the most trusted and respected pool service companies in Florida, expanding our services while maintaining the same level of quality and commitment.', es: 'Ser reconocidos como una de las empresas de servicios de piscinas más confiables y respetadas de Florida, expandiendo nuestros servicios mientras mantenemos el mismo nivel de calidad y compromiso.' },
  about_values_title: { en: 'Values', es: 'Valores' },
  about_value_1_title: { en: 'Customer Commitment:', es: 'Compromiso con el Cliente:' },
  about_value_1_text: { en: 'Personalized attention for every project.', es: 'Atención personalizada para cada proyecto.' },
  about_value_2_title: { en: 'Uncompromising Quality:', es: 'Calidad sin Compromisos:' },
  about_value_2_text: { en: 'Highest standards in every detail.', es: 'Los más altos estándares en cada detalle.' },
  about_value_3_title: { en: 'Trust & Transparency:', es: 'Confianza y Transparencia:' },
  about_value_3_text: { en: 'Honesty and clear communication.', es: 'Honestidad y comunicación clara.' },
  about_value_4_title: { en: 'Operational Excellence:', es: 'Excelencia Operativa:' },
  about_value_4_text: { en: 'Efficient processes and consistent results.', es: 'Procesos eficientes y resultados constantes.' },

  // Portfolio
  portfolio_hero_title: { en: 'Real Projects. Real Results.', es: 'Proyectos Reales. Resultados Reales.' },
  portfolio_hero_subtitle: { en: 'Take a look at some of our recent work and see how we transform pools and outdoor spaces with attention to detail.', es: 'Eche un vistazo a algunos de nuestros trabajos recientes y vea cómo transformamos piscinas y espacios al aire libre con atención al detalle.' },
  portfolio_cta_title: { en: 'Thinking about upgrading your pool?', es: '¿Está pensando en actualizar su piscina?' },
  portfolio_cta_subtitle: { en: 'Let us help you create the outdoor space of your dreams.', es: 'Permítanos ayudarle a crear el espacio al aire libre de sus sueños.' },

  // Testimonials
  testimonials_hero_title: { en: 'Trusted by Homeowners Across Central Florida', es: 'Con la Confianza de Propietarios en Toda Florida Central' },
  testimonials_hero_subtitle: { en: 'Our clients choose us for reliability, quality, and peace of mind. Here’s what they have to say.', es: 'Nuestros clientes nos eligen por nuestra confiabilidad, calidad y tranquilidad. Esto es lo que tienen que decir.' },
  testimonials_cta_title: { en: 'Experience the difference yourself.', es: 'Experimente la diferencia usted mismo.' },

  // Contact
  contact_hero_title: { en: 'Contact Us', es: 'Contáctenos' },
  contact_hero_subtitle: { en: 'Have questions or ready to get started? Reach out today and let our team take care of your pool.', es: '¿Tiene preguntas o está listo para empezar? Contáctenos hoy y deje que nuestro equipo se encargue de su piscina.' },
  contact_info_title: { en: 'Contact Information', es: 'Información de Contacto' },
  contact_phone_label: { en: 'Phone', es: 'Teléfono' },
  contact_email_label: { en: 'Email', es: 'Correo Electrónico' },
  contact_address_label: { en: 'Address', es: 'Dirección' },
  contact_hours_title: { en: 'Business Hours', es: 'Horario de Atención' },
  contact_mon_fri_label: { en: 'Monday to Friday', es: 'Lunes a Viernes' },
  contact_estimates_title: { en: 'Free In-Person Estimates', es: 'Presupuestos Presenciales Gratuitos' },
  contact_estimates_text: { en: 'We provide expert, on-site evaluations to give you the most accurate pricing and solutions for your pool.', es: 'Ofrecemos evaluaciones expertas en el lugar para brindarle los precios y soluciones más precisos para su piscina.' },
  form_success_title: { en: 'Thank You!', es: '¡Gracias!' },
  form_success_message: { en: 'We have received your request and will contact you shortly to schedule your free in-person estimate.', es: 'Hemos recibido su solicitud y nos pondremos en contacto con usted pronto para programar su presupuesto presencial gratuito.' },
  form_send_another: { en: 'Send another request', es: 'Enviar otra solicitud' },
  form_select_service: { en: 'Select a service', es: 'Seleccione un servicio' },
  service_leak_detection: { en: 'Leak Detection', es: 'Detección de Fugas' },
  service_cleaning_maintenance: { en: 'Pool Cleaning & Maintenance', es: 'Limpieza y Mantenimiento de Piscinas' },
  service_pool_deck_renovations: { en: 'Pool and Deck Renovations', es: 'Renovaciones de Piscinas y Terrazas' },
  service_equipment_repair: { en: 'Equipment Repair & Installation', es: 'Reparación e Instalación de Equipos' },
  service_paver_sealing: { en: 'Paver Sealing', es: 'Sellado de Adoquines' },
  service_acid_wash: { en: 'Acid Wash & Deep Cleaning', es: 'Lavado Ácido y Limpieza Profunda' },
  footer_description: { en: 'Serving Central Florida with excellence since 2005. Your trusted partner for pool maintenance, leak detection, and renovations.', es: 'Sirviendo a Florida Central con excelencia desde 2005. Su socio de confianza para el mantenimiento de piscinas, detección de fugas y renovaciones.' },
  footer_quick_links: { en: 'Quick Links', es: 'Enlaces Rápidos' },
  footer_contact_us: { en: 'Contact Us', es: 'Contáctenos' },
  footer_free_estimates: { en: 'Free In-Person Estimates', es: 'Presupuestos Presenciales Gratuitos' },
  footer_rights: { en: 'All rights reserved.', es: 'Todos los derechos reservados.' },
};
